
package ca.bcit.comp4656.employee.xml;

import javax.xml.ws.WebFault;
import ca.bcit.comp4656.employee.types.FindEmployeeFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "findEmployeeFault", targetNamespace = "http://www.bcit.ca/comp4656/employee/types/")
public class FindError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FindEmployeeFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FindError(String message, FindEmployeeFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FindError(String message, FindEmployeeFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ca.bcit.comp4656.employee.types.FindEmployeeFault
     */
    public FindEmployeeFault getFaultInfo() {
        return faultInfo;
    }

}
