
package ca.bcit.comp4656.employee.xml;

import javax.xml.ws.WebFault;
import ca.bcit.comp4656.employee.types.GetEmployeesFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "getEmployeesFault", targetNamespace = "http://www.bcit.ca/comp4656/employee/types/")
public class GetEmployeesError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetEmployeesFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetEmployeesError(String message, GetEmployeesFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetEmployeesError(String message, GetEmployeesFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ca.bcit.comp4656.employee.types.GetEmployeesFault
     */
    public GetEmployeesFault getFaultInfo() {
        return faultInfo;
    }

}
